---
- name: Deploy local
  hosts: "sonet_local"
  roles:
    - role: './sonet/roles/services'
    - role: './sonet/roles/generate_compose'

# - name: Generate compose file for docker-mashine
#   hosts: "sonet_docker_mashine"
#   roles:
#     - role: './sonet/roles/services'
#     - role: './sonet/roles/generate_compose'
