---
all:
  hosts:
    generate_local:
      ansible_connection: local
      ansible_python_interpreter: python3
      build_path: "{{ local_playbook_path }}/build/sonet_local/source"
      docker_data_path: "{{ local_playbook_path }}/build/sonet_local/data"
      backup_path: "{{ local_playbook_path }}/build/sonet_local/backup"
      pki_path: "{{ local_playbook_path }}/build/sonet_local/pki"
      docker_bind_ip: 127.0.0.1
      generate_service_certs: true
      include_service:
        - caddy
        - coredns
        - openldap
        - phpldapadmin
        - redmine
        - excalidraw
        - gitlab
        - roundcube
        - mailserv
        - storage
        - nextcloud
        - portainer
        - adminer
        - grafana
        - monitoring
        - control-files
