---
coredns_docker_service: |2
    coredns:
      container_name: {{project}}-coredns
      image: {{registry_url}}{{project}}-coredns:latest
      restart: always
      volumes:
        - {{docker_data_path}}/coredns/etc/coredns:/etc/coredns
      entrypoint:
        - "/entrypoint.sh"
        - "/coredns/coredns"
        - "-conf"
        - "/etc/coredns/Corefile"
      expose:
        - '53'
        - '53/udp'
      ports:
        - '{{bind_ip}}53:53'
        - '{{bind_ip}}53:53/udp'
      networks:
        - net
