---
coredns:
  # root_forward: [ '8.8.8.8' ]
  zones:
    - zonefile: "{{ conf['ldap_domain'] }}.zone"
      name: "{{ conf['ldap_domain'] }}"
      domain_name: "@"
      name_server_fqdn: "ns.{{ conf['ldap_domain'] }}."
      admin_email: "root@ns.{{ conf['ldap_domain'] }}."
      members:
        - { hostname: '@', type: 'NS', address: "ns.{{ conf['ldap_domain'] }}." }
        - { hostname: '', type: 'MX', address: "10 mail.{{ conf['ldap_domain'] }}." }
        - { hostname: "ns.{{ conf['ldap_domain'] }}.", type: 'A', address: '10.20.1.1' }
        - { hostname: "mail.{{ conf['ldap_domain'] }}.", type: 'A', address: '10.20.1.2' }
        - { hostname: "{{ conf['ldap_hostname'] }}.{{ conf['ldap_domain'] }}.", type: 'A', address: '10.20.1.3' }
    - zonefile: '1.20.10.in-addr.arpa.zone'
      name: '1.20.10.in-addr.arpa'
      domain_name: "@"
      name_server_fqdn: "ns.{{ conf['ldap_domain'] }}."
      admin_email: "root@ns.{{ conf['ldap_domain'] }}."
      members:
        - { hostname: '@', type: 'NS', address: "ns.{{ conf['ldap_domain'] }}." }
        - { hostname: "ns.{{ conf['ldap_domain'] }}.", type: 'PTR', address: '10.20.1.1' }
        - { hostname: "mail.{{ conf['ldap_domain'] }}.", type: 'PTR', address: '10.20.1.2' }
        - { hostname: "{{ conf['ldap_hostname'] }}.{{ conf['ldap_domain'] }}.", type: 'PTR', address: '10.20.1.3' }
