---
openldap:
  ldap_log_level: "256"
  ldap_organisation: "Sonet"
  ldap_domain: "{{ conf['ldap_domain'] }}"
  ldap_base_dn: "{{ conf['ldap_base_dn'] }}"
  ldap_hostname: "{{ conf['ldap_hostname'] }}"
  ldap_admin_password: "{{ ldap_admin_password }}"
  ldap_config_password: "{{ ldap_config_password }}"
  ldap_readonly_user: 'true'
  ldap_readonly_user_username: "readonly"
  ldap_readonly_user_password: "{{ ldap_readonly_user_password }}"
  ldap_tls: "true"
  ldap_tls_crt_filename: "cert.crt"
  ldap_tls_key_filename: "cert.key"
  ldap_tls_dh_param_filename: "dhparam.pem"
  ldap_tls_ca_crt_filename: "ca.crt"
  ldap_tls_enforce: "false"
  ldap_tls_cipher_suite: "SECURE256:-VERS-SSL3.0"
  ldap_tls_verify_client: "try"
  keep_existing_config: "false"
  ldap_remove_config_after_setup: "true"
  ldap_ssl_helper_prefix: "ldap"
  preset_ldiff:
    users:
      lpervov: { person: true, id: 20201, sn: Первов, displayName: "Первов Л.", givenName: Лев, ou: Редакция, userPassword: lpervov }
      avtorov: { person: true, id: 20202, sn: Второв, displayName: "Второв А.", givenName: Антон, ou: Редакция, userPassword: avtorov }
      itretiev: { person: true, id: 20203, sn: Третьев, displayName: "Третьев А.", givenName: Игорь, ou: Редакция, userPassword: itretiev }
      pchetvertov: { person: true, id: 20204, sn: Четвертов, displayName: "Четвертов П.", givenName: Павел, ou: Редакция, userPassword: pchetvertov }
      opyatov: { person: true, id: 20205, sn: Пятов, displayName: "Пятов О.", givenName: Олег, ou: Редакция, userPassword: opyatov }
      redmine: { person: false, userPassword: "{{ conf['redmine_admin_mail_account_password'] }}" }
      gitlab: { person: false, userPassword: "{{ conf['gitlab_mail_account_password'] }}" }
      nextcloud: { person: false, userPassword: "{{ conf['nextcloud_admin_mail_account_password'] }}" }
    groups:
      gitlab_users:
        description: "Пользователи GitLab"
        members:
          - gitlab
          - lpervov
          - avtorov
      redmine_users:
        description: "Пользователи Redmine"
        members:
          - redmine
          - lpervov
          - avtorov
      nextcloud_users:
        description: "Пользователи NextCloud"
        members:
          - nextcloud
          - lpervov
          - avtorov
          - pchetvertov
          - opyatov
      storage_admins:
        description: "Администраторы SFTP"
        members:
          - lpervov
      managers:
        description: "Руководство"
        members:
          - lpervov
      colleagues:
        description: "Сотрудники"
        members:
          - lpervov
          - avtorov
          - itretiev
          - pchetvertov
          - opyatov
