---
openldap:
  ldap_organisation: "Sonet"
  preset_ldiff:
    users:
      lpervov: { person: true, id: 20201, sn: Первов, displayName: "Первов Л.", givenName: Лев, ou: Редакция, userPassword: "{{ vault_ldap_user_default_password }}" }
      avtorov: { person: true, id: 20202, sn: Второв, displayName: "Второв А.", givenName: Антон, ou: Редакция, userPassword: "{{ vault_ldap_user_default_password }}" }
      itretiev: { person: true, id: 20203, sn: Третьев, displayName: "Третьев А.", givenName: Игорь, ou: Редакция, userPassword: "{{ vault_ldap_user_default_password }}" }
      pchetvertov: { person: true, id: 20204, sn: Четвертов, displayName: "Четвертов П.", givenName: Павел, ou: Редакция, userPassword: "{{ vault_ldap_user_default_password }}" }
      opyatov: { person: true, id: 20205, sn: Пятов, displayName: "Пятов О.", givenName: Олег, ou: Редакция, userPassword: "{{ vault_ldap_user_default_password }}" }
      redmine: { person: false, userPassword: "{{ conf['redmine_admin_mail_account_password'] }}" }
      gitlab: { person: false, userPassword: "{{ conf['gitlab_mail_account_password'] }}" }
      nextcloud: { person: false, userPassword: "{{ conf['nextcloud_admin_mail_account_password'] }}" }
    groups:
      gitlab_users:
        description: "Пользователи GitLab"
        members:
          - gitlab
          - lpervov
          - avtorov
      grafana_admins:
        description: "Администраторы Grafana"
        members:
          - lpervov
      grafana_editors:
        description: "Пользователи Grafana"
        members:
          - avtorov
          - itretiev
      redmine_users:
        description: "Пользователи Redmine"
        members:
          - redmine
          - lpervov
          - avtorov
      nextcloud_users:
        description: "Пользователи NextCloud"
        members:
          - nextcloud
          - lpervov
          - avtorov
          - pchetvertov
          - opyatov
      storage_admins:
        description: "Администраторы SFTP"
        members:
          - lpervov
      managers:
        description: "Руководство"
        members:
          - lpervov
      colleagues:
        description: "Сотрудники"
        members:
          - lpervov
          - avtorov
          - itretiev
          - pchetvertov
          - opyatov
