---
openldap:
  ldap_log_level: "256"
  ldap_organisation: "Sonet"
  ldap_domain: "{{ conf['ldap_domain'] }}"
  ldap_base_dn: "{{ conf['ldap_base_dn'] }}"
  ldap_hostname: "{{ conf['ldap_hostname'] }}"
  ldap_admin_password: "{{ ldap_admin_password }}"
  ldap_config_password: "{{ ldap_config_password }}"
  ldap_readonly_user: 'true'
  ldap_readonly_user_username: "readonly"
  ldap_readonly_user_password: "{{ ldap_readonly_user_password }}"
  ldap_tls: "true"
  ldap_tls_crt_filename: "cert.crt"
  ldap_tls_key_filename: "cert.key"
  ldap_tls_dh_param_filename: "dhparam.pem"
  ldap_tls_ca_crt_filename: "ca.crt"
  ldap_tls_enforce: "false"
  ldap_tls_cipher_suite: "SECURE256:-VERS-SSL3.0"
  ldap_tls_verify_client: "try"
  keep_existing_config: "false"
  ldap_remove_config_after_setup: "true"
  ldap_ssl_helper_prefix: "ldap"
  preset_ldiff:
    users:
      ltolstoy: { person: true, id: 20201, sn: Толстой, displayName: "Толстой Л.", givenName: Лев, ou: Редакция, userPassword: ltolstoy }
      achehov: { person: true, id: 20202, sn: Чехов, displayName: "Чехов А.", givenName: Антон, ou: Редакция, userPassword: achehov }
      redmine: { person: false, userPassword: "{{ conf['redmine_admin_mail_account_password'] }}" }
      gitlab: { person: false, userPassword: "{{ conf['gitlab_mail_account_password'] }}" }
    groups:
      gitlab:
        - gitlab
        - ltolstoy
        - achehov
      redmine:
        - redmine
        - ltolstoy
        - achehov
      storage:
        - ltolstoy
