---
caddy_docker_service: |2
    caddy:
      container_name: {{project}}-caddy
      image:  {{registry_url}}{{project}}-caddy:latest
      restart: always
      volumes:
        - {{docker_data_path}}/caddy/config:/config
        - {{docker_data_path}}/caddy/data:/data
        - {{docker_data_path}}/caddy/opt/caddy:/opt/caddy
        - {{docker_data_path}}/caddy/var/log/caddy:/var/log/caddy
        - {{docker_data_path}}/caddy/etc/pki/tls:/etc/pki/tls
        - {{docker_data_path}}/caddy/etc/caddy:/etc/caddy
      entrypoint:
        - "/entrypoint.sh"
        - "/usr/bin/caddy"
        - "run"
        - "--config"
        - "/etc/caddy/Caddyfile"
      ports:
        - "{{bind_ip}}80:80/tcp"
        - "{{bind_ip}}443:443/tcp"
      networks:
        - net
