---
mailserv:
  hostname: mail
  domain: "{{ conf['domain'] }}"
  ldap_url: "ldap://{{ conf['ldap_hostname'] }}:389"
  ldap_base_dn: "{{ conf['ldap_base_dn'] }}"
  ldap_bind_dn: "cn={{ openldap['ldap_readonly_user_username'] }},{{ conf['ldap_base_dn'] }}"
  ldap_bind_pw: "{{ openldap['ldap_readonly_user_password'] }}"
  ssl_crt_filename: cert.crt
  ssl_key_filename: cert.key
  ssl_ca_crt_filename: ca.crt
  ssl_dhparam_1024: dhparam.pem
  ssl_dhparam_512: dhparam.pem

  dovecot:
    uris: "ldap://{{ conf['ldap_hostname'] }}:389"
    base: "ou=users,{{ conf['ldap_base_dn'] }}"
    user_attrs: "mailuserquota=quota_rule=*:bytes=%$"
    user_filter: "(&(objectClass=mailAccount)(mail=%u)(mailenable=OK))"
    pass_attrs: "mail=user,userPassword=password"
    pass_filter: "(&(objectClass=mailAccount)(cn=%n)(mailenable=OK))"
    iterate_attrs: "mail=user"
    iterate_filter: "(objectClass=mailAccount)"

  postfix:
    accounts:
      search_base: "ou=users,{{ conf['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailAccount)(mailenable=OK)(mail=%s))"
      result_attribute: mailbox
    aliases:
      search_base: "ou=users,{{ conf['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailAccount)(mailalias=%s)(mailenable=OK))"
      result_attribute: mail
    domains:
      search_base: "ou=mailDomains,{{ conf['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailDomain)(virtualdomain=%s))"
      result_attribute: virtualdomain
    senders:
      search_base: "ou=users,{{  conf['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailAccount)(mailenable=OK)(|(mail=%s)(mailalias=%s)))"
      result_attribute: mail,mailalias
      special_result_attribute: mailaliasmember
    valiases:
      search_base: "ou=mailAliases,{{ conf['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailAlias)(mailalias=%s)(mailenable=OK))"
      result_attribute: mail
      special_result_attribute: mailaliasmember

  backup_cron_exp: 30 4 * * *  # every day at 4:30am
  backup_ttl: 15   # delete backups that are over 15 days

  roundcube:
    ldap_inc: |
      // Type of LDAP cache. Supported values: 'db', 'apc' and 'memcache'.
      $config['ldap_cache'] = 'db';

      // Lifetime of LDAP cache. Possible units: s, m, h, d, w
      $config['ldap_cache_ttl'] = '10m';

      //Разрешить поиск и автодополнение из массива AD
      $rcmail_config['autocomplete_addressbooks'] = array('sql','AD');

      $config['ldap_public'] = array(
          //Имя массива, в котором выполняется поиск
          'AD' =>array (
              'name' => 'LDAP', //Отображаемое имя в интерфейсе WEBMail Roundcube
              'hosts' => array('{{ conf['ldap_hostname'] }}'), //IP адрес или ДНС имя
              'sizelimit' => 600,
              'port' => 389,
              'use_tls' => false,
              'user_specific' => false,
              'base_dn' => '{{ conf['ldap_base_dn'] }}', //Где выполнять поиск
              'bind_dn' => 'cn={{ openldap['ldap_readonly_user_username'] }},{{ conf['ldap_base_dn'] }}', //Авторизация на контроллере домена
              'bind_pass' => '{{ openldap['ldap_readonly_user_password'] }}', //Авторизация на контроллере домена
              'writable' => false,
              'ldap_version' => 3,
              'search_fields' => array(
              'mail',
              'cn',
              'sn',
              ),
              'name_field' => 'displayName',
              'email_field' => 'mail',
              'surname_field' => 'sn',
              'firstname_field' => 'givenName',
              //Можно добавить немного дополнительной информации в адресной книге
              // 'organization_field'     => 'company',
              // 'jobtitle_field'    => 'title',
              // 'department_field'   => 'department',
              //Порядок сортировки
              'sort' => 'sn',
              'scope' => 'sub', //Выполнять поиск по всему каталогу LDAP // search mode: sub|base|list
              'filter' => '(&(objectClass=person)(mailenable=OK)(mail=*))',
              //'filter' => '(&(mail=*)(|(&(objectcategory=person)(!(objectClass=computer)))(objectClass=group)))',
              'global_search' => true,
              'fuzzy_search' => true
          ),
      );
