---
mailserv:
  hostname: mail
  domain: "{{ conf['domain'] }}"
  ldap_url: "ldap://{{ conf['ldap_hostname'] }}:389"
  ldap_base_dn: "{{ openldap['ldap_base_dn'] }}"
  ldap_bind_dn: "cn={{ openldap['ldap_readonly_user_username'] }},{{ openldap['ldap_base_dn'] }}"
  ldap_bind_pw: "{{ openldap['ldap_readonly_user_password'] }}"
  ssl_crt_filename: cert.crt
  ssl_key_filename: cert.key
  ssl_ca_crt_filename: ca.crt
  ssl_dhparam_1024: dhparam.pem
  ssl_dhparam_512: dhparam.pem

  dovecot:
    uris: "ldap://{{ conf['ldap_hostname'] }}:389"
    base: "ou=users,{{ openldap['ldap_base_dn'] }}"
    user_attrs: "mailuserquota=quota_rule=*:bytes=%$"
    user_filter: "(&(objectClass=mailAccount)(mail=%u)(mailenable=OK))"
    pass_attrs: "mail=user,userPassword=password"
    pass_filter: "(&(objectClass=mailAccount)(cn=%n)(mailenable=OK))"
    iterate_attrs: "mail=user"
    iterate_filter: "(objectClass=mailAccount)"

  postfix:
    accounts:
      search_base: "ou=users,{{ openldap['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailAccount)(mailenable=OK)(mail=%s))"
      result_attribute: mailbox
    aliases:
      search_base: "ou=users,{{ openldap['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailAccount)(mailalias=%s)(mailenable=OK))"
      result_attribute: mail
    domains:
      search_base: "ou=mailDomains,{{ openldap['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailDomain)(virtualdomain=%s))"
      result_attribute: virtualdomain
    senders:
      search_base: "ou=users,{{  openldap['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailAccount)(mailenable=OK)(|(mail=%s)(mailalias=%s)))"
      result_attribute: mail,mailalias
      special_result_attribute: mailaliasmember
    valiases:
      search_base: "ou=mailAliases,{{ openldap['ldap_base_dn'] }}"
      query_filter: "(&(objectClass=mailAlias)(mailalias=%s)(mailenable=OK))"
      result_attribute: mail
      special_result_attribute: mailaliasmember

  backup_cron_exp: 30 4 * * *  # every day at 4:30am
  backup_ttl: 15   # delete backups that are over 15 days
