---
mailserv:
  hostname: mail
  domain: "{{ conf['domain'] }}"
  ldap_url: "ldap://{{ conf['ldap_hostname'] }}:389"
  ldap_base_dn: "{{ conf['ldap_base_dn'] }}"
  ldap_bind_dn: "cn={{ conf['ldap_readonly_user_username'] }},{{ conf['ldap_base_dn'] }}"
  ldap_bind_pw: "{{ conf['ldap_readonly_user_password'] }}"
  ssl_crt_filename: cert.crt
  ssl_key_filename: cert.key
  ssl_ca_crt_filename: ca.crt
  ssl_dhparam_1024: dhparam.pem
  ssl_dhparam_512: dhparam.pem

  backup_cron_exp: 30 4 * * *  # every day at 4:30am
  backup_ttl: 15   # delete backups that are over 15 days

mailserv_docker_service: |2
    mailserv:
      container_name: {{project}}-mailserv
      image:  {{registry_url}}{{project}}-mailserv:latest
      restart: always
      volumes:
        - {{docker_data_path}}/mailserv/var/mail:/var/mail
        - {{docker_data_path}}/mailserv/data/backup:/data/backup
      ports:
        # Expose smtp, pop3, imap, smtp (submission), imap ssl, managesieve and dovecot replication ports
        - "{{bind_ip}}25:25/tcp"
        - "{{bind_ip}}143:143/tcp"
        - "{{bind_ip}}587:587/tcp"
        - "{{bind_ip}}993:993/tcp"
      domainname: "{{ mailserv['domain'] }}"
      hostname: "{{ mailserv['hostname'] }}"
      networks:
        net:
          aliases:
            - "{{ mailserv['hostname'] }}"
            - "{{ mailserv['hostname'] }}.{{ mailserv['domain'] }}"
