---
roundcube:
  ldap_inc: |
    // Type of LDAP cache. Supported values: 'db', 'apc' and 'memcache'.
    $config['ldap_cache'] = 'db';

    // Lifetime of LDAP cache. Possible units: s, m, h, d, w
    $config['ldap_cache_ttl'] = '10m';

    //Разрешить поиск и автодополнение из массива AD
    $rcmail_config['autocomplete_addressbooks'] = array('sql','AD');

    $config['ldap_public'] = array(
        //Имя массива, в котором выполняется поиск
        'AD' =>array (
            'name' => 'LDAP', //Отображаемое имя в интерфейсе WEBMail Roundcube
            'hosts' => array('{{ conf['ldap_hostname'] }}'), //IP адрес или ДНС имя
            'sizelimit' => 600,
            'port' => 389,
            'use_tls' => false,
            'user_specific' => false,
            'base_dn' => '{{ conf['ldap_base_dn'] }}', //Где выполнять поиск
            'bind_dn' => 'cn={{ conf['ldap_readonly_user_username'] }},{{ conf['ldap_base_dn'] }}', //Авторизация на контроллере домена
            'bind_pass' => '{{ conf['ldap_readonly_user_password'] }}', //Авторизация на контроллере домена
            'writable' => false,
            'ldap_version' => 3,
            'search_fields' => array(
            'mail',
            'cn',
            'sn',
            ),
            'name_field' => 'displayName',
            'email_field' => 'mail',
            'surname_field' => 'sn',
            'firstname_field' => 'givenName',
            //Можно добавить немного дополнительной информации в адресной книге
            // 'organization_field'     => 'company',
            // 'jobtitle_field'    => 'title',
            // 'department_field'   => 'department',
            //Порядок сортировки
            'sort' => 'sn',
            'scope' => 'sub', //Выполнять поиск по всему каталогу LDAP // search mode: sub|base|list
            'filter' => '(&(objectClass=person)(mailenable=OK)(mail=*))',
            //'filter' => '(&(mail=*)(|(&(objectcategory=person)(!(objectClass=computer)))(objectClass=group)))',
            'global_search' => true,
            'fuzzy_search' => true
        ),
    );

roundcube_docker_service: |2
    roundcube:
      container_name: {{project}}-roundcube
      image:  {{registry_url}}{{project}}-roundcube:latest
      restart: unless-stopped
      volumes:
        - {{docker_data_path}}/roundcube/roundcube/var/www/html:/var/www/html
      entrypoint:
        - "/wait-for-postgres.sh"
        - "--host=roundcubedb"
        - "--db=roundcube"
        - "--user=roundcube"
        - "--pass=roundcube"
        - "--"
        - "/docker-entrypoint.sh"
        - "apache2-foreground"
      environment:
        ROUNDCUBEMAIL_DB_TYPE: pgsql
        ROUNDCUBEMAIL_DB_HOST: roundcubedb
        ROUNDCUBEMAIL_DB_NAME: roundcube
        ROUNDCUBEMAIL_DB_USER: roundcube
        ROUNDCUBEMAIL_DB_PASSWORD: roundcube
        ROUNDCUBEMAIL_SKIN: elastic
        ROUNDCUBEMAIL_DEFAULT_HOST: tls://{{ mailserv['hostname'] }}.{{ mailserv['domain'] }}
        ROUNDCUBEMAIL_SMTP_SERVER: tls://{{ mailserv['hostname'] }}.{{ mailserv['domain'] }}
      depends_on:
        - roundcubedb
      networks:
        - net

    roundcubedb:
      image:  {{registry_url}}{{project}}-roundcubedb:latest
      container_name: {{project}}-roundcubedb
      restart: always
      volumes:
        - {{docker_data_path}}/roundcube/postgres-data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: roundcube
        POSTGRES_PASSWORD: roundcube
        POSTGRES_DB: roundcube
        PGDATA: /var/lib/postgresql/data
      networks:
        - net
