---
redmine:
  ldap_auth_name: "{{ openldap['ldap_organisation'] }}"
  ldap_host: "{{ conf['ldap_hostname'] }}"
  ldap_account: "cn={{ conf['ldap_readonly_user_username'] }},{{ conf['ldap_base_dn'] }}"
  ldap_account_password: "{{ conf['ldap_readonly_user_password'] }}"
  ldap_base_dn: "ou=users,{{ conf['ldap_base_dn'] }}"
  ldap_attr_login: cn
  ldap_attr_firstname: givenName
  ldap_attr_lastname: sn
  ldap_attr_mail: mail
  ldap_filter: "(&(objectClass=person)(memberOf=cn=redmine_users,ou=groups,{{ conf['ldap_base_dn'] }}))"
  smtp_address: "{{ mailserv['hostname'] }}.{{ mailserv['domain'] }}"
  smtp_port: 25
  smtp_authentication: ":login"
  smtp_domain: "{{ mailserv['domain'] }}"
  smtp_user_name: 'redmine'
  smtp_password: "{{ conf['redmine_admin_mail_account_password'] }}"
  plugins_and_themes:
    - { url: "https://github.com/fraoustin/RTMaterial/archive/refs/heads/master.zip", dest: "{{ build_path }}/images/redmine/service/redmine/themes/RTMaterial.zip" }
    - { url: "https://github.com/Nitrino/flatly_light_redmine/archive/refs/heads/master.zip", dest: "{{ build_path }}/images/redmine/service/redmine/themes/flatly_light_redmine.zip" }
    - { url: "https://github.com/mrliptontea/PurpleMine2/archive/refs/heads/master.zip", dest: "{{ build_path }}/images/redmine/service/redmine/themes/PurpleMine2.zip" }
    - { url: "https://github.com/makotokw/redmine-theme-gitmike/archive/refs/heads/master.zip", dest: "{{ build_path }}/images/redmine/service/redmine/themes/redmine-theme-gitmike.zip" }
    - { url: "https://github.com/AlphaNodes/additional_tags/archive/refs/heads/master.zip", dest: "{{ build_path }}/images/redmine/service/redmine/plugins/additional_tags.zip" }
    - { url: "https://github.com/AlphaNodes/additionals/archive/refs/heads/master.zip", dest: "{{ build_path }}/images/redmine/service/redmine/plugins/additionals.zip" }
    - { url: "https://github.com/danmunn/redmine_dmsf/archive/refs/heads/master.zip", dest: "{{ build_path }}/images/redmine/service/redmine/plugins/redmine_dmsf.zip" }
    - { url: "https://github.com/akpaevj/dashboard/archive/refs/heads/master.zip", dest: "{{ build_path }}/images/redmine/service/redmine/plugins/dashboard.zip" }

redmine_docker_service: |2
    redmine:
      image:  {{registry_url}}{{project}}-redmine:latest
      container_name: {{project}}-redmine
      restart: always
      environment:
        REDMINE_DB_POSTGRES: "redminedb"
        REDMINE_DB_DATABASE: "redmine"
        REDMINE_DB_USERNAME: "postgres"
        REDMINE_DB_PASSWORD: "password"
        REDMINE_PLUGINS_MIGRATE: "true"
      volumes:
        - {{docker_data_path}}/redmine/redmine-data/usr/src/redmine/files:/usr/src/redmine/files
      depends_on:
        - redminedb
      networks:
        - net

    redminedb:
      image: {{registry_url}}{{project}}-redminedb:latest
      container_name: {{project}}-redminedb
      restart: always
      volumes:
        - {{docker_data_path}}/redmine/postgres-data/var/lib/postgresql/data:/var/lib/postgresql/data
      environment:
        POSTGRES_USERNAME: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "redmine"
        PGDATA: "/var/lib/postgresql/data"
      networks:
        - net
