---
redmine:
  ldap_auth_name: "{{ openldap['ldap_organisation'] }}"
  ldap_host: "{{ conf['ldap_hostname'] }}"
  ldap_account: "cn={{ openldap['ldap_readonly_user_username'] }},{{ openldap['ldap_base_dn'] }}"
  ldap_account_password: "{{ openldap['ldap_readonly_user_password'] }}"
  ldap_base_dn: "ou=users,{{ openldap['ldap_base_dn'] }}"
  ldap_attr_login: cn
  ldap_attr_firstname: givenName
  ldap_attr_lastname: sn
  ldap_attr_mail: mail
  ldap_filter: "(&(objectClass=person)(memberOf=cn=redmine_users,ou=groups,{{ openldap['ldap_base_dn'] }}))"
  smtp_address: "{{ mailserv['hostname'] }}.{{ mailserv['domain'] }}"
  smtp_port: 25
  smtp_authentication: ":login"
  smtp_domain: "{{ mailserv['domain'] }}"
  smtp_user_name: 'redmine'
  smtp_password: "{{ conf['redmine_admin_mail_account_password'] }}"
  plugins_and_themes:
    - { url: "https://github.com/fraoustin/RTMaterial.git", tag: "0.1.8", dest: "{{ local_path }}/images/redmine/service/redmine/themes/RTMaterial" }
    - { url: "https://github.com/Nitrino/flatly_light_redmine.git", tag: "v0.2.4", dest: "{{ local_path }}/images/redmine/service/redmine/themes/flatly_light_redmine" }
    - { url: "https://github.com/mrliptontea/PurpleMine2.git", tag: "v2.15.0", dest: "{{ local_path }}/images/redmine/service/redmine/themes/PurpleMine2" }
    - { url: "https://github.com/makotokw/redmine-theme-gitmike.git", tag: " v1.2.1", dest: "{{ local_path }}/images/redmine/service/redmine/themes/redmine-theme-gitmike" }
    - { url: "https://github.com/AlphaNodes/additional_tags.git", tag: "1.0.0", dest: "{{ local_path }}/images/redmine/service/redmine/plugins/additional_tags" }
    - { url: "https://github.com/AlphaNodes/additionals.git", tag: "3.0.2", dest: "{{ local_path }}/images/redmine/service/redmine/plugins/additionals" }
    - { url: "https://github.com/danmunn/redmine_dmsf.git", tag: "v2.4.6", dest: "{{ local_path }}/images/redmine/service/redmine/plugins/redmine_dmsf" }
    - { url: "https://github.com/akpaevj/dashboard.git", tag: "1.0.10", dest: "{{ local_path }}/images/redmine/service/redmine/plugins/dashboard" }
