---
nextcloud:
  ldap_host: ldap
  ldap_port: 389
  ldap_base: "{{ conf['ldap_base_dn'] }}"
  ldap_agent_name: "cn={{ openldap['ldap_readonly_user_username'] }},{{ conf['ldap_base_dn'] }}"
  ldap_agent_password: "{{ openldap['ldap_readonly_user_password'] }}"
  ldap_email_attribute: mail
  ldap_gid_number: gidNumber
  ldap_group_display_name: description
  ldap_group_filter: "(&(|(objectclass=groupOfUniqueNames))(|(cn=colleagues)(cn=managers)))"
  ldap_group_filter_objectclass: groupOfUniqueNames
  ldap_group_member_assoc_attr: uniqueMember
  ldap_login_filter: "(&(&(|(objectclass=person))(|(memberof=cn=nextcloud_users,ou=groups,{{ conf['ldap_base_dn'] }})))(|(cn=%uid)))"
  ldap_login_filter_attributes: cn
  ldap_userdisplay_name: displayname
  ldap_user_filter: "(&(|(objectclass=person))(|(memberof=cn=nextcloud_users,ou=groups,{{ conf['ldap_base_dn'] }})))"
  ldap_user_filter_groups: nextcloud
  ldap_user_filter_objectclass: person
  ldap_configuration_active: 1
  apps:
    - { url: "https://github.com/nextcloud/mail/releases/download/v1.9.5/mail.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/mail.tar.gz" }
    - { url: "https://github.com/nextcloud/groupfolders/releases/download/v9.0.1/groupfolders.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/groupfolders.tar.gz" }
    - { url: "https://github.com/nextcloud/announcementcenter/releases/download/v5.0.0/announcementcenter-5.0.0.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/announcementcenter.tar.gz" }
    - { url: "https://github.com/nextcloud/contacts/releases/download/v3.5.1/contacts.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/contacts.tar.gz" }
    - { url: "https://github.com/nextcloud/notes/releases/download/v4.0.4/notes.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/notes.tar.gz" }
    - { url: "https://github.com/nextcloud/forms/releases/download/v2.2.4/forms.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/forms.tar.gz" }
    - { url: "https://github.com/nextcloud/news/releases/download/15.4.2/news.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/news.tar.gz" }
    - { url: "https://github.com/nextcloud/calendar/releases/download/v2.2.1/calendar.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/calendar.tar.gz" }
    - { url: "https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/download/v6.3.0/onlyoffice.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/onlyoffice.tar.gz" }
    - { url: "https://github.com/pawelrojek/nextcloud-drawio/releases/download/v.1.0.0/drawio-v1.0.0.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/drawio.tar.gz" }
    - { url: "https://github.com/icewind1991/files_markdown/releases/download/v2.3.3/files_markdown.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/files_markdown.tar.gz" }
    - { url: "https://github.com/ACTom/files_mindmap/releases/download/v0.0.24/files_mindmap-0.0.24.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/files_mindmap.tar.gz" }
    - { url: "https://github.com/jhass/nextcloud-keeweb/releases/download/v0.6.5/keeweb-0.6.5.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/keeweb-0.6.5.tar.gz" }
    - { url: "https://github.com/nickv-nextcloud/event_update_notification/releases/download/v1.2.0/event_update_notification-1.2.0.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/event_update_notification-1.2.0.tar.gz" }
    - { url: "https://h-software.de/nextcloud_apps/ldapcontacts/ldapcontacts-2.0.5.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/ldapcontacts-2.0.5.tar.gz" }
    # can't connect to server
    # - { url: "https://git.mdns.eu/nextcloud/passwords/-/jobs/12123/artifacts/raw/passwords.tar.gz", dest: "{{ build_path }}/images/nextcloud/service/nextcloud/apps/passwords.tar.gz" }
