---
grafana:
  ldap_host: "{{ conf['ldap_hostname'] }}"
  ldap_account: "cn={{ conf['ldap_readonly_user_username'] }},{{ conf['ldap_base_dn'] }}"
  ldap_account_password: "{{ conf['ldap_readonly_user_password'] }}"

  ldap_base_dn: "ou=users,{{ conf['ldap_base_dn'] }}"
  ldap_search_filter: "(cn=%s)"

  ldap_name: "givenName"
  ldap_surname: "sn"
  ldap_username: "cn"
  ldap_member_of: "memberOf"
  ldap_email:  "email"

  admin_group_dn: "cn=grafana_admins,ou=groups,{{ conf['ldap_base_dn'] }}"
  editor_group_dn: "cn=grafana_editors,ou=groups,{{ conf['ldap_base_dn'] }}"

  plugins:
    - flant-statusmap-panel
    - grafana-piechart-panel
    - grafana-polystat-panel
    - michaeldmoore-multistat-panel
    - vonage-status-panel
    - yesoreyeram-boomtable-panel
    - camptocamp-prometheus-alertmanager-datasource
    - natel-influx-admin-panel

monitoring_docker_service: |2
    cadvisor:
      container_name: {{project}}-cadvisor
      image: {{registry_url}}{{project}}-cadvisor:latest
      restart: unless-stopped
      ports:
        - "{{bind_ip}}8080:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker:/var/lib/docker:ro
      networks:
        - net

    prometheus:
      container_name: {{project}}-prometheus
      image: {{registry_url}}{{project}}-prometheus:latest
      user: "0"
      restart: unless-stopped
      ports:
        - "{{bind_ip}}9090:9090"
      volumes:
        - {{docker_data_path}}/prometheus/data:/data
        - {{docker_data_path}}/prometheus/etc/prometheus:/etc/prometheus
      entrypoint:
        - "/entrypoint.sh"
        - "/bin/prometheus"
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/data'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      depends_on:
        - cadvisor
      networks:
        - net

    grafana:
      container_name: {{project}}-grafana
      image: {{registry_url}}{{project}}-grafana:latest
      user: "0"
      restart: unless-stopped
      ports:
        - "{{bind_ip}}3000:3000"
      environment:
        GF_AUTH_BASIC_ENABLED: "false"
        GF_RENDERING_SERVER_URL: "http://renderer:8081/render"
        GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
        GF_LOG_FILTERS: "rendering:debug"
        GF_SERVER_ROOT_URL: "https://grafana.{{ conf['domain'] }}/"
        GF_SERVER_DOMAIN: '{{ conf['domain'] }}'
      volumes:
        - {{docker_data_path}}/grafana/var/lib/grafana:/var/lib/grafana
        - {{docker_data_path}}/grafana/etc/grafana:/etc/grafana
      entrypoint:
        - "/entrypoint.sh"
        - "/run.sh"
      networks:
        - net

    renderer:
      container_name: {{project}}-renderer
      image: {{registry_url}}{{project}}-grafana-image-renderer:latest
      restart: unless-stopped
      environment:
        ENABLE_METRICS: 'true'
      depends_on:
        - grafana
      networks:
        - net

    node-exporter:
      container_name: {{project}}-node-exporter
      image: {{registry_url}}{{project}}-node-exporter:latest
      restart: unless-stopped
      ports:
        - "{{bind_ip}}9100:9100"
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
      networks:
        - net

    pushgateway:
      container_name: {{project}}-pushgateway
      image: {{registry_url}}{{project}}-pushgateway:latest
      restart: unless-stopped
      ports:
        - "{{bind_ip}}9091:9091"
      networks:
        - net
