---
monitoring_docker_service: |2
    cadvisor:
      container_name: {{project}}-cadvisor
      image: {{registry_url}}{{project}}-cadvisor:latest
      restart: unless-stopped
      ports:
        - "{{bind_ip}}8080:8080"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker:/var/lib/docker:ro
      networks:
        - net

    prometheus:
      container_name: {{project}}-prometheus
      image: {{registry_url}}{{project}}-prometheus:latest
      user: "0"
      restart: unless-stopped
      ports:
        - "{{bind_ip}}9090:9090"
      volumes:
        - {{docker_data_path}}/prometheus/data:/data
        - {{docker_data_path}}/prometheus/etc/prometheus:/etc/prometheus
      entrypoint:
        - "/entrypoint.sh"
        - "/bin/prometheus"
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/data'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      depends_on:
        - cadvisor
      networks:
        - net

    node-exporter:
      container_name: {{project}}-node-exporter
      image: {{registry_url}}{{project}}-node-exporter:latest
      restart: unless-stopped
      ports:
        - "{{bind_ip}}9100:9100"
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
      networks:
        - net

    pushgateway:
      container_name: {{project}}-pushgateway
      image: {{registry_url}}{{project}}-pushgateway:latest
      restart: unless-stopped
      ports:
        - "{{bind_ip}}9091:9091"
      networks:
        - net
