---
grafana:
  ldap_host: "{{ conf['ldap_hostname'] }}"
  ldap_account: "cn={{ conf['ldap_readonly_user_username'] }},{{ conf['ldap_base_dn'] }}"
  ldap_account_password: "{{ conf['ldap_readonly_user_password'] }}"

  ldap_base_dn: "ou=users,{{ conf['ldap_base_dn'] }}"
  ldap_search_filter: "(cn=%s)"

  ldap_name: "givenName"
  ldap_surname: "sn"
  ldap_username: "cn"
  ldap_member_of: "memberOf"
  ldap_email:  "email"

  admin_group_dn: "cn=grafana_admins,ou=groups,{{ conf['ldap_base_dn'] }}"
  editor_group_dn: "cn=grafana_editors,ou=groups,{{ conf['ldap_base_dn'] }}"

  plugins:
    - flant-statusmap-panel
    - grafana-piechart-panel
    - grafana-polystat-panel
    - michaeldmoore-multistat-panel
    - vonage-status-panel
    - yesoreyeram-boomtable-panel
    - camptocamp-prometheus-alertmanager-datasource
    - natel-influx-admin-panel
