---
portainer_docker_service: |2
    portainer:
      image:  {{registry_url}}{{project}}-portainer:latest
      container_name: {{project}}-portainer
      restart: always
      command: --admin-password "{{ conf['portainer_admin_account_password'] }}" -H unix:///var/run/docker.sock
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - {{docker_data_path}}/portainer/data:/data
      environment:
        - VIRTUAL_HOST=portainer.{{ conf['domain'] }}
        - VIRTUAL_PORT=9000
      networks:
        - net
